;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		cua-delete-region
		my-semantic-complete-self-insert
		))

(setq mc/cmds-to-run-once
      '(
		cua-exchange-point-and-mark
		delete-window
		keyboard-escape-quit
		previous-buffer
		scroll-right
		shell
		text-scale-increase
		))
